server:
  port: 8765
spring:
  redis:
    host: localhost
    database: 0
    port: 6379
   datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 600000
      maximum-pool-size: 500
      max-lifetime: 1800000
      minimum-idle: 20
      validation-timeout: 3000
      idle-timeout: 60000
      connection-init-sql: SET NAMES utf8mb4
    name: mysql
    url: jdbc:mysql://localhost:3306/user?ullNamePatternMatchesAll=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #扫描哪个包下的mapper映射文件
  mapper-locations: classpath:mapper/*.xml
  #type-aliases-package: com.mr.test_orderclass.po
